# This file is here to let us know when Renovate updates. Whenever Renovate has
# a new version it will process this file and create a PR with the changelog. It
# has no use outside of that.
FROM renovate/renovate:31
