#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -e
echo "Linting commits before push..."
while IFS= read -r line; do
  parts=($line)
  old="${parts[3]}"
  new="${parts[1]}"

  if [ "${old}" = "0000000000000000000000000000000000000000" ]; then
    npx commitlint -f 'master' -t "$new"
  else
    npx commitlint -f "$old" -t "$new"
  fi
done < /dev/stdin

echo "All commits matched enforced style!"

npm run lint
npm run build
npm run gendoc
./scripts/examples/build-all
