#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -e
echo "Linting commits before push..."
while IFS= read -r line; do
  parts=($line)
  old="${parts[3]}"
  new="${parts[1]}"

  commits=$(git log --pretty=format:%s "$old...$new")

  while IFS= read -r commit; do
    npx commitlint <<< "$commit"
  done <<< "$commits"
done < /dev/stdin

echo "All commits matched enforced style!"
